sudo: false
dist: trusty
language: elixir
elixir:
  - 1.9.0
otp_release:
  - 22.0.7
services:
  - postgresql
addons:
  postgresql: "9.6"
cache:
  directories:
    - _deps
    - _build
env:
  global:
    - DATABASE_URL=ecto://postgres:@localhost/current
script:
  - mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    recipients:
      - arumery@cars.com
    on_success: change
    on_failure: change
